web:
  addr: 127.0.0.1:9628
# sqlite3
db:
  file: ./test.db
ldap:
  addr: "127.0.0.1:389"
  rootDN: "ou=tech,dc=test,dc=com"
  username: "test"
  password: "test"
log:
  # log level
  # FINEST/FINE/DEBUG/TRACE/INFO/WARNING/ERROR/CRITICAL
  # 0/1/2/3/4/5/6/7/8
  # level: 0
  conf: config/log.xml

  